name: CI

on:
  push:
    branches: [ master, 1.x ]

  pull_request:
    branches: [ master, 1.x ]

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@v1
    with:
      os: 'ubuntu-latest'
      version: '14, 16, 18'
